### ISSUE TITLE
Error Analysis: Widget crash - Both in full screen or inline in jupyter

### ISSUE THREAD

**Issue by nushib** [microsoft/responsible-ai-widgets#181]
Happened in 2 occasions:
1- When clicking the first cell in a 1-dimensional heatmap.
2- When clicking Cohort Info. 

This is the last part of the error in console. 

Uncaught TypeError: Cannot read property 'label' of undefined
    at (index):371456
    at Array.map (<anonymous>)
    at ErrorCohort.cohortFiltersToString ((index):371453)
    at (index):371503
    at Array.map (<anonymous>)
    at ErrorCohort.cohortCompositeFiltersToString ((index):371501)
    at (index):371506
    at Array.map (<anonymous>)
    at ErrorCohort.cohortCompositeFiltersToString ((index):371501)
    at (index):371506
(index):338687 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in TreeViewRenderer (created by ErrorAnalysisView)

=====================================
This is the full error

Download the React DevTools for a better development experience: https://fb.me/react-devtools
(index):338687 Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state

Please update the following components: DropdownBase, ResizeGroupBase
printWarning @ (index):338687
(index):338687 Warning: Using UNSAFE_componentWillUpdate in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.

Please update the following components: OverflowSetBase
printWarning @ (index):338687
(index):338687 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of WithResponsiveMode which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
    in div (created by DropdownBase)
    in DropdownBase (created by WithResponsiveMode)
    in WithResponsiveMode (created by StyledWithResponsiveMode)
    in StyledWithResponsiveMode (created by commandBarButtonAs)
    in commandBarButtonAs (created by OuterWithDefaultRender)
    in OuterWithDefaultRender (created by OverflowSetBase)
    in div (created by OverflowSetBase)
    in div (created by OverflowSetBase)
    in OverflowSetBase (created by StyledOverflowSetBase)
    in StyledOverflowSetBase (created by ResizeGroupBase)
    in div (created by FocusZone)
    in FocusZone (created by ResizeGroupBase)
    in div (created by ResizeGroupBase)
    in div (created by ResizeGroupBase)
    in div (created by ResizeGroupBase)
    in ResizeGroupBase (created by CommandBarBase)
    in CommandBarBase (created by StyledCommandBarBase)
    in StyledCommandBarBase (created by MainMenu)
    in div (created by MainMenu)
    in div (created by MainMenu)
    in MainMenu (created by ErrorAnalysisDashboard)
    in div (created by ErrorAnalysisDashboard)
    in ErrorAnalysisDashboard (created by ErrorAnalysis)
    in ErrorAnalysis (created by App)
    in App
    in StrictMode
printWarning @ (index):338687
(index):364550 Warning: Can't call setState on a component that is not yet mounted. This is a no-op, but it might indicate a bug in your application. Instead, assign to `this.state` directly or define a `state = {};` class property with the desired state in the TreeViewRenderer component.
printWarning @ (index):364550
(index):364550 Warning: Can't call forceUpdate on a component that is not yet mounted. This is a no-op, but it might indicate a bug in your application. Instead, assign to `this.state` directly or define a `state = {};` class property with the desired state in the TreeViewRenderer component.
printWarning @ (index):364550
(index):338687 Warning: Using UNSAFE_componentWillMount in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.

Please update the following components: CalloutContentBase, Popup
printWarning @ (index):338687
(index):338687 Warning: Using UNSAFE_componentWillUpdate in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.

Please update the following components: CalloutContentBase
printWarning @ (index):338687
(index):338687 Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state

Please update the following components: Autofill, ComboBox
printWarning @ (index):338687
(index):364550 Warning: Can't call setState on a component that is not yet mounted. This is a no-op, but it might indicate a bug in your application. Instead, assign to `this.state` directly or define a `state = {};` class property with the desired state in the MatrixArea component.
printWarning @ (index):364550
(index):371456 Uncaught TypeError: Cannot read property 'label' of undefined
    at (index):371456
    at Array.map (<anonymous>)
    at ErrorCohort.cohortFiltersToString ((index):371453)
    at (index):371503
    at Array.map (<anonymous>)
    at ErrorCohort.cohortCompositeFiltersToString ((index):371501)
    at (index):371506
    at Array.map (<anonymous>)
    at ErrorCohort.cohortCompositeFiltersToString ((index):371501)
    at (index):371506
(index):338687 Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state

Please update the following components: FocusTrapZone
printWarning @ (index):338687
(index):358126 The above error occurred in the <PredictionPath> component:
    in PredictionPath (created by CohortInfo)
    in div (created by CohortInfo)
    in div (created by CohortInfo)
    in div (created by PanelBase)
    in div (created by PanelBase)
    in div (created by PanelBase)
    in div (created by FocusTrapZone)
    in FocusTrapZone (created by PanelBase)
    in div (created by PanelBase)
    in div (created by Popup)
    in Popup (created by PanelBase)
    in div (created by FabricBase)
    in FabricBase (created by StyledFabricBase)
    in StyledFabricBase (created by LayerBase)
    in span (created by LayerBase)
    in LayerBase (created by Context.Consumer)
    in CustomizedLayer (created by StyledCustomizedLayer)
    in StyledCustomizedLayer (created by PanelBase)
    in PanelBase (created by StyledPanelBase)
    in StyledPanelBase (created by CohortInfo)
    in CohortInfo (created by ErrorAnalysisDashboard)
    in div (created by FabricBase)
    in FabricBase (created by StyledFabricBase)
    in StyledFabricBase (created by LayerBase)
    in span (created by LayerBase)
    in LayerBase (created by Context.Consumer)
    in CustomizedLayer (created by StyledCustomizedLayer)
    in StyledCustomizedLayer (created by ErrorAnalysisDashboard)
    in Customizer (created by ErrorAnalysisDashboard)
    in div (created by ErrorAnalysisDashboard)
    in div (created by ErrorAnalysisDashboard)
    in ErrorAnalysisDashboard (created by ErrorAnalysis)
    in ErrorAnalysis (created by App)
    in App
    in StrictMode

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ (index):358126
(index):349701 Uncaught TypeError: Cannot read property 'label' of undefined
    at (index):371456
    at Array.map (<anonymous>)
    at ErrorCohort.cohortFiltersToString ((index):371453)
    at (index):371503
    at Array.map (<anonymous>)
    at ErrorCohort.cohortCompositeFiltersToString ((index):371501)
    at (index):371506
    at Array.map (<anonymous>)
    at ErrorCohort.cohortCompositeFiltersToString ((index):371501)
    at (index):371506
(index):338687 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in TreeViewRenderer (created by ErrorAnalysisView)
printWarning @ (index):338687
DevTools failed to load SourceMap: Could not load content for http://localhost:5000/runtime.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://localhost:5000/polyfills.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://localhost:5000/vendor.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://localhost:5000/main.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by imatiach-msft** [comment]
closing based on conversation with @nushib as fixed or not reproduced
