### ISSUE TITLE
Error Analysis: Explanations among cohorts do not seem that different

### ISSUE THREAD

**Issue by nushib** [microsoft/responsible-ai-widgets#197]
No matter which sub cohort I pick, the ordering of feature importances is always the same. This may be an issue with the mimic explainer but it is important to understand before we use it anywhere else. Seems like the explainer doesn't really change much depending on the instance.

**Comment by imatiach-msft** [comment]
closing as discussed, seems original issue occurred when model was trained with small number of trees, and explanation was trivial
