### ISSUE TITLE
Error Analysis: Local Explanation - It is not clear which color is each data point

### ISSUE THREAD

**Issue by nushib** [microsoft/responsible-ai-widgets#198]
I selected two data points here: one correct and one incorrect. One can generate the graph but it is not clear what is what? 

![image](https://user-images.githubusercontent.com/4303632/101724975-95d77c80-3a64-11eb-9075-86a7b92f152a.png)

**Comment by imatiach-msft** [comment]
added colors with PR https://github.com/microsoft/responsible-ai-widgets/pull/335
