### ISSUE TITLE
Export atomic pages

### ISSUE THREAD

**Issue by rihorn2** [microsoft/responsible-ai-widgets#2]
Pages in dashboards should be exportable and then consumable as standalone components.
Currently, they rely on data processing that happens in the main component, this should be extracted to a static method, so exportable page components can have interfaces that are a subset of the main page interface and use its helper functions for processing.

**Comment by imatiach-msft** [comment]
closing as everything is componentized well now (like how we can add separate components to model analysis dashboard)
