### ISSUE TITLE
Zoom interaction on Tree map

### ISSUE THREAD

**Issue by HyemiSong** [microsoft/responsible-ai-widgets#200]
The zoom interaction is unavailable before you click the canvas area. Without clicking the background, the scroll reaction is a vertical scroll, not zooming.

<img width="1409" alt="Screen Shot 2020-12-10 at 9 29 14 AM" src="https://user-images.githubusercontent.com/1608824/101807948-91de4580-3aca-11eb-99e1-85b194103d92.png">

**Comment by imatiach-msft** [comment]
closing as zoom has been disabled in latest widget based on new design (and for integration in model analysis dashboard), so this issue is no longer relevant
