### ISSUE TITLE
The height of the feature list panel (fullscreen mode)

### ISSUE THREAD

**Issue by HyemiSong** [microsoft/responsible-ai-widgets#204]
The height of the feature list panel should be fixed as the window height (fullscreen mode)
The apply btn is always shown at the bottom. The panel itself has its own scroll.

<img width="1437" alt="Screen Shot 2020-12-10 at 10 54 02 AM" src="https://user-images.githubusercontent.com/1608824/101816904-7aa55500-3ad6-11eb-9fdd-868ad92185d6.png">

**Comment by imatiach-msft** [comment]
closing as fixed with https://github.com/microsoft/responsible-ai-widgets/pull/341
