### ISSUE TITLE
Displaying "Error explorer" in the breadcrumb

### ISSUE THREAD

**Issue by HyemiSong** [microsoft/responsible-ai-widgets#209]
The current app doesn't show "Error explorer" in the breadcrumb, but it should display Error explorer with the black text.

<img width="1440" alt="Screen Shot 2020-12-10 at 11 34 17 AM" src="https://user-images.githubusercontent.com/1608824/101840101-5b1f2400-3af8-11eb-986b-89829bd64bfe.png">
<img width="1440" alt="Screen Shot 2020-12-10 at 11 53 02 AM" src="https://user-images.githubusercontent.com/1608824/101840108-5d817e00-3af8-11eb-96c2-7a5cfe6b2892.png">

**Comment by imatiach-msft** [comment]
fixed as part of #328
