### ISSUE TITLE
[Error Analysis] Treemap node hover interaction/position error

### ISSUE THREAD

**Issue by HyemiSong** [microsoft/responsible-ai-widgets#228]
1.
The tooltip appears when you hover on the stroke.
It disappears when you move the mouse to the node fill area.

2.
The tooltip's position is different from designs. See the below screenshots and the figma file.

1.
<img width="1440" alt="Screen Shot 2020-12-18 at 5 44 45 PM" src="https://user-images.githubusercontent.com/1608824/102677778-d1570280-4158-11eb-8092-ac95f25256e4.png">
<img width="1440" alt="Screen Shot 2020-12-18 at 5 44 53 PM" src="https://user-images.githubusercontent.com/1608824/102677779-d2882f80-4158-11eb-8e0d-daa9620395e3.png">
<img width="1440" alt="Screen Shot 2020-12-18 at 5 44 57 PM" src="https://user-images.githubusercontent.com/1608824/102677780-d320c600-4158-11eb-91f9-1e3f5a3e539e.png">

2.
<img width="738" alt="Screen Shot 2020-12-18 at 5 52 29 PM" src="https://user-images.githubusercontent.com/1608824/102677943-fbf58b00-4159-11eb-931d-82aed62106c9.png">
<img width="841" alt="Screen Shot 2020-12-18 at 5 52 51 PM" src="https://user-images.githubusercontent.com/1608824/102677946-fef07b80-4159-11eb-838b-14b07ef2f0df.png">

**Comment by imatiach-msft** [comment]
closing as this has been resolved with @xuke444 PR https://github.com/microsoft/responsible-ai-widgets/pull/402
there were minor style changes from this design though by our PM
