### ISSUE TITLE
[Error Analysis] Left alignment of all interpretML tabs

### ISSUE THREAD

**Issue by HyemiSong** [microsoft/responsible-ai-widgets#233]
They are left-aligned. Please refer to the fluent style for the margin between tabs 

<img width="1440" alt="Screen Shot 2020-12-18 at 9 03 12 PM" src="https://user-images.githubusercontent.com/1608824/102681213-73381880-4174-11eb-9d84-e4eb7cd9c6af.png">

<img width="855" alt="Screen Shot 2020-12-18 at 9 04 55 PM" src="https://user-images.githubusercontent.com/1608824/102681233-b0040f80-4174-11eb-8c7c-3536734010f0.png">

**Comment by imatiach-msft** [comment]
fixed with PR https://github.com/microsoft/responsible-ai-widgets/pull/342
