### ISSUE TITLE
[Error Analysis] All select btn should be hidden or removed

### ISSUE THREAD

**Issue by HyemiSong** [microsoft/responsible-ai-widgets#238]
No one will choose all data points. Even if you select all, the selected instances are not displayed in the inspect view.

<img width="1436" alt="Screen Shot 2020-12-20 at 11 33 25 PM" src="https://user-images.githubusercontent.com/1608824/102751078-e8921d80-431b-11eb-9dc0-1fed8b3f1694.png">

**Comment by imatiach-msft** [comment]
closing as this has been fixed with #292
