### ISSUE TITLE
[Error Analysis] After saving a cohort, display a msg bar.

### ISSUE THREAD

**Issue by HyemiSong** [microsoft/responsible-ai-widgets#242]
<img width="1440" alt="Screen Shot 2020-12-21 at 12 41 17 PM" src="https://user-images.githubusercontent.com/1608824/102820655-786eb080-438a-11eb-93d6-c0a87b28921b.png">

<img width="786" alt="Screen Shot 2020-12-21 at 12 46 34 PM" src="https://user-images.githubusercontent.com/1608824/102820719-91776180-438a-11eb-9e48-466bf45b0881.png">

**Comment by imatiach-msft** [comment]
closing as this message bar has been added as part of PR
https://github.com/microsoft/responsible-ai-widgets/pull/1005
