### ISSUE TITLE
[Error Analysis] Dashboard > Data explorer > Explanation > Data explorer > filter should be retained

### ISSUE THREAD

**Issue by HyemiSong** [microsoft/responsible-ai-widgets#247]
This is already defined previously, but I would like to highlight this flow.

<img width="799" alt="Screen Shot 2020-12-21 at 11 19 55 PM" src="https://user-images.githubusercontent.com/1608824/102860642-1b531900-43e3-11eb-8e95-997600425b22.png">
<img width="799" alt="Screen Shot 2020-12-21 at 11 20 01 PM" src="https://user-images.githubusercontent.com/1608824/102860645-1bebaf80-43e3-11eb-9125-884532344493.png">
<img width="799" alt="Screen Shot 2020-12-21 at 11 19 55 PM" src="https://user-images.githubusercontent.com/1608824/102860648-1d1cdc80-43e3-11eb-9019-a9a2377b5e02.png">

**Comment by imatiach-msft** [comment]
These are now retained, fixed as part of PR https://github.com/microsoft/responsible-ai-widgets/pull/278
