### ISSUE TITLE
[Error Analysis] Local explanation > numbers about selected datapoints should be shown

### ISSUE THREAD

**Issue by HyemiSong** [microsoft/responsible-ai-widgets#251]
This is different from the design. The numbers about what you selected are important to review the current status.

<img width="839" alt="Screen Shot 2020-12-21 at 11 42 02 PM" src="https://user-images.githubusercontent.com/1608824/102862573-23608800-43e6-11eb-85bd-963c23a7db31.png">
<img width="1354" alt="Screen Shot 2020-12-21 at 11 41 46 PM" src="https://user-images.githubusercontent.com/1608824/102862623-383d1b80-43e6-11eb-9db5-7a471c49f871.png">

**Comment by imatiach-msft** [comment]
note: will avoid adding denominator "/ number" since that can become confusing in big-data case where we currently downsample

**Comment by imatiach-msft** [comment]
fixed with PR https://github.com/microsoft/responsible-ai-widgets/pull/358
