### ISSUE TITLE
[Error Analysis]Local explanation > adding colored rects before a row

### ISSUE THREAD

**Issue by HyemiSong** [microsoft/responsible-ai-widgets#252]
To match the colors between the list and the bars in the chart.

<img width="821" alt="Screen Shot 2020-12-21 at 11 43 26 PM" src="https://user-images.githubusercontent.com/1608824/102862757-6fabc800-43e6-11eb-8c19-1c330c2014d3.png">

**Comment by imatiach-msft** [comment]
added colors with PR https://github.com/microsoft/responsible-ai-widgets/pull/335
