### ISSUE TITLE
[Error Analysis] Remove the blue effect around the dropdown on the top

### ISSUE THREAD

**Issue by HyemiSong** [microsoft/responsible-ai-widgets#255]
<img width="439" alt="Screen Shot 2020-12-21 at 11 54 14 PM" src="https://user-images.githubusercontent.com/1608824/102863769-e6959080-43e7-11eb-92af-905fc674a7bc.png">

**Comment by imatiach-msft** [comment]
I don't think this is actually recommended due to accessibility - if the user tabs through components they should see the blue effect
