### ISSUE TITLE
[Error Analysis]: Mismatch between what is selected and what is shown in local explanations wrt indexes

### ISSUE THREAD

**Issue by nushib** [microsoft/responsible-ai-widgets#311]
Reproducing steps:

1- Create cohort for not married people in UCI Income dataset
2- Go to local explanation
3- Pick the first row from incorrect and some others from correct
4- Inspect

![image](https://user-images.githubusercontent.com/4303632/107104387-49938900-67d6-11eb-8f4b-fff64a3e59d7.png)

and

![image](https://user-images.githubusercontent.com/4303632/107104440-7ba4eb00-67d6-11eb-8918-d36a724df2ed.png)

**Comment by imatiach-msft** [comment]
as discussed this may have been fixed with this PR already: https://github.com/microsoft/responsible-ai-widgets/pull/292
please reopen if you still see the issue on latest - it seems it was fixed when you upgraded to latest package version
