### ISSUE TITLE
[Error Analysis]: X axis in data explorer missing for classification outcome

### ISSUE THREAD

**Issue by nushib** [microsoft/responsible-ai-widgets#312]
![image](https://user-images.githubusercontent.com/4303632/107104524-ebb37100-67d6-11eb-8bd3-8a735cbf412d.png)

**Comment by imatiach-msft** [comment]
I believe this was already fixed with https://github.com/microsoft/responsible-ai-widgets/pull/322

**Comment by imatiach-msft** [comment]
closing as it was verified this was fixed by @nushib
