### ISSUE TITLE
[ErrorAnalysis] [Explanation]: The number of bins in the data explorer doesn't change

### ISSUE THREAD

**Issue by nushib** [microsoft/responsible-ai-widgets#389]
Thought we had created an issue on this but could not find it. Feel free to merge or delete if needed.

**Comment by imatiach-msft** [comment]
manipulating bins has been added in PR:
https://github.com/microsoft/responsible-ai-widgets/pull/824
closing this issue

**Comment by imatiach-msft** [comment]
related issue:
https://github.com/microsoft/responsible-ai-widgets/issues/572
