### ISSUE TITLE
Unable to render dashboards in databricks

### ISSUE THREAD

**Issue by jakeatmsft** [microsoft/responsible-ai-widgets#400]
following example notebook:
https://github.com/microsoft/responsible-ai-widgets/blob/main/notebooks/erroranalysis-interpretability-dashboard-breast-cancer.ipynb

When trying to render ExplanationDashboard, dashboard does not display only the following output message.

cmd:
ExplanationDashboard(global_explanation, model, dataset=x_test, true_y=y_test)

output:
Interpret started at None
<IPython.core.display.HTML object>
Out[20]: <raiwidgets.explanation_dashboard.ExplanationDashboard at 0x7f6dd954dc90>

**Comment by jakeatmsft** [comment]
Databricks cluster info:
Runtime -7.0 (includes Apache Spark 3.0.0, Scala 2.12)

Installed libraries:
Name
Type
Status
Source

applicationinsights==0.11.5
PyPI
-

fairlearn
PyPI
-

sklearn_pandas
PyPI
-

flask_cors
PyPI
-

interpret-community[visualization]
PyPI
-

azureml-sdk[explain,interpret,databricks, contrib, contrib-interpret, interpret, contrib-fairness]
PyPI
-

azureml-contrib-fairness
PyPI
-

azureml-contrib-interpret
PyPI
-

mlflow
PyPI
-

azureml-mlflow
PyPI
-

azureml-core
PyPI
-

azureml-dataprep[pandas]
PyPI
-

mpld3
PyPI
-

networkx
PyPI
-

nltk
PyPI
-

raiwidgets
PyPI
-

**Comment by imatiach-msft** [comment]
closing as this has been fixed with #424
