### ISSUE TITLE
[Error Analysis]: Clarify in the documentation the model / library / parameters being used to train the error analysis tree. Expose the parameters to the interface and allow to retrain.

### ISSUE THREAD

**Issue by nushib** [microsoft/responsible-ai-widgets#573]
Suggested by Melanie Fernandez Pradier:

I would love to get further information of what model is being trained on the residuals, what parameters are being used/how I can adjust these, etc.

**Comment by imatiach-msft** [comment]
The parameters for the tree view are now shown and user can change them:
https://github.com/microsoft/responsible-ai-widgets/pull/913
there are tooltips for them, and the parameters can also be seen in the error analysis dashboard widget doc
