### ISSUE TITLE
[Error Analysis]: Error rate in the heatmap is not multiplied by 100 

### ISSUE THREAD

**Issue by nushib** [microsoft/responsible-ai-widgets#766]
Version of raiwidgets:
Python 3.7.11 (default, Jul 27 2021, 09:42:29) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import raiwidgets
>>>
>>> print(raiwidgets.__version__)
0.9.2
>>>

Steps to reproduce:
- Created two cohorts from the default tree: married and not married cohorts
- Switched back to the all data cohort
- The error rate in the heatmap does not show 23.x% but 0.24. It may be that it just needs to be multiplied by 100.
- The same happens in the cohort list (see the second figure below)

![image](https://user-images.githubusercontent.com/4303632/128615852-5bacc34b-db45-4c6c-a3a0-674d9f1b9e59.png)

![image](https://user-images.githubusercontent.com/4303632/128616045-063ca4c7-9e63-48f5-9556-bc7e6d53aa08.png)

**Comment by imatiach-msft** [comment]
PR has been merged and the fix is in raiwidget 0.11.0 which was just released to pypi, so closing this issue
