### ISSUE TITLE
[Error Analysis] The dashboard crashes when selecting one row to inspect from the raw data table

### ISSUE THREAD

**Issue by nushib** [microsoft/responsible-ai-widgets#768]
Version of raiwidgets:
import raiwidgets

print(raiwidgets.version)
0.9.2

Steps to reproduce with the census dataset:

- Go to Explanation --> Local Explanations --> Incorrect Predictions
- Pick one (e.g. record with id 41) from the table and click inspect
- The dashboard crashes either before or after clicking inspect

![image](https://user-images.githubusercontent.com/4303632/128616003-f372f03f-0d96-484a-993e-6b4191cb0193.png)

**Comment by MasaNahti** [comment]
I have the same issue with raiwidgets==0.9.2.  There are some React warnings and errors displayed in the browser DevTools, but I am not sure how or if they are related to this.

**Comment by imatiach-msft** [comment]
this is fixed with PR:
https://github.com/microsoft/responsible-ai-widgets/pull/887

**Comment by imatiach-msft** [comment]
PR has been merged and the fix is in raiwidget 0.11.0 which was just released to pypi, so closing this issue
