### ISSUE TITLE
Long Feature Names in the Feature List

### ISSUE THREAD

**Issue by ilmarinen** [microsoft/responsible-ai-widgets#857]
1. I have a dataset where the feature names are long (20 to 40 characters in length).
2. When I browse the list of features in the feature list, the names are clipped.
3. It would be nice to allow me to see the full name when I hover over a feature.

Please see attached images.
<img width="1264" alt="Screen Shot 2021-09-10 at 9 26 21 AM" src="https://user-images.githubusercontent.com/680818/132886799-7605564b-48e1-49d0-a137-05b21e7eb999.png">
<img width="345" alt="Screen Shot 2021-09-10 at 9 26 31 AM" src="https://user-images.githubusercontent.com/680818/132886821-a0e53658-aca1-4440-9f18-b1a90dc9ff89.png">

**Comment by imatiach-msft** [comment]
closing as this was just fixed recently by yongjiaaaa:

![image](https://user-images.githubusercontent.com/24683184/133638951-0c39a267-c842-4949-b568-6d46c01b94da.png)

https://github.com/microsoft/responsible-ai-widgets/pull/825
