### ISSUE TITLE
Clearing the Port in use

### ISSUE THREAD

**Issue by alexmar123** [microsoft/responsible-ai-widgets#863]
Hi,

When re-running the ErrorAnalysisDashboard using the same port as a previous run, it returns an error saying that the Address is already in use, is there any way to clear the port/s in use?

OSError: [Errno 98] Address already in use: (url, port)

**Comment by imatiach-msft** [comment]
@alexmar123 are you not able to specify a different port?  I think it's cleared by the OS after some time and we don't have control over that?

**Comment by gaugup** [comment]
@alexmar123, does @imatiach-msft's response help your query? If so maybe, we can close this issue as there is nothing to address here?

Regards,

**Comment by gaugup** [comment]
Closing due to no response from the submitter.
