### ISSUE TITLE
[Error Analysis] [Model Analysis] Heatmap shows the overall error rate of the "just created cohort" even if the cohort wasn't shifted

### ISSUE THREAD

**Issue by nushib** [microsoft/responsible-ai-widgets#884]
1- Using erroranalysis-interpretability-dashboard-census.ipynb
2- Create cohort for not married individuals through the tree
3- Go to the heatmap

The heatmap should be showing the error rate for the whole data and not only for the just created cohort.

![image](https://user-images.githubusercontent.com/4303632/134073844-29877547-2287-4310-848b-495f7ddc2aa9.png)

**Comment by imatiach-msft** [comment]
I am not currently able to reproduce it, I think it may have been fixed already in the past.

I created the unmarried cohort using "save cohort", and then right away I went to the heatmap. However, the heatmap showed the global statistics for all data, and not just the unmarried cohort.
This is with the latest raiwidgets package 0.14.0.

**Comment by imatiach-msft** [comment]
closing as fixed, verified with @nushib this issue is resolved
