### ISSUE TITLE
[Error Analysis] [Model Analysis] Ordering direction for the heatmap axes (two numerical features)

### ISSUE THREAD

**Issue by nushib** [microsoft/responsible-ai-widgets#885]
1- Select two numerical features in the heatmap using any notebook. 

As of now, it is difficult to interpret the heatmap to match small values in X with small values in Y. It would be most useful if Y is sorted in the opposite direction where higher values are on top and lower values at the bottom.

![image](https://user-images.githubusercontent.com/4303632/134074191-7faa8704-96ab-4fdd-af41-1b09efefa94a.png)

**Comment by imatiach-msft** [comment]
closing as this was fixed as part of PR:
https://github.com/microsoft/responsible-ai-widgets/pull/904
